---
- include: compat.yml

- include: include_vars.yml

- include: epel.yml
  when: ansible_distribution == 'CentOS'

- include: Debian.yml
  when: ansible_os_family == 'Debian'

- include: install_package_names.yml
